nodeLinker: hoisted
shamefullyHoist: true
packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@shopify/react-native-skia': true
  esbuild: true
  '@biomejs/biome': true
  unrs-resolver: true
  sharp: true
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.14'
  - '@biomejs/cli-darwin-arm64@2.5.14'
  - '@biomejs/cli-darwin-x64@2.5.14'
  - '@biomejs/cli-linux-arm64-musl@2.5.14'
  - '@biomejs/cli-linux-arm64@2.5.14'
  - '@biomejs/cli-linux-x64-musl@2.5.14'
  - '@biomejs/cli-linux-x64@2.5.14'
  - '@biomejs/cli-win32-arm64@2.5.14'
  - '@biomejs/cli-win32-x64@2.5.14'
  - '@tanstack/query-core@5.103.1'
  - '@tanstack/react-query@5.103.1'
